// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdGI9oPWbQr6eUH7KBysVTs5SPm0lF6ro',
    appId: '1:957338800443:web:734654a7c58139ca7ce71e',
    messagingSenderId: '957338800443',
    projectId: 'tp3-firebase-ac93e',
    authDomain: 'tp3-firebase-ac93e.firebaseapp.com',
    storageBucket: 'tp3-firebase-ac93e.appspot.com',
    measurementId: 'G-NY7CZWSSTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs02B67cX13xqYuQmonNYCaRCSkTKTZ1E',
    appId: '1:957338800443:android:988d43b5f72c0ded7ce71e',
    messagingSenderId: '957338800443',
    projectId: 'tp3-firebase-ac93e',
    storageBucket: 'tp3-firebase-ac93e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCefyTh5SlynVPX3HycMZ-WtqSg5gheR5o',
    appId: '1:957338800443:ios:0db00f981050b1597ce71e',
    messagingSenderId: '957338800443',
    projectId: 'tp3-firebase-ac93e',
    storageBucket: 'tp3-firebase-ac93e.appspot.com',
    iosBundleId: 'org.sarah.tp1Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCefyTh5SlynVPX3HycMZ-WtqSg5gheR5o',
    appId: '1:957338800443:ios:0db00f981050b1597ce71e',
    messagingSenderId: '957338800443',
    projectId: 'tp3-firebase-ac93e',
    storageBucket: 'tp3-firebase-ac93e.appspot.com',
    iosBundleId: 'org.sarah.tp1Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdGI9oPWbQr6eUH7KBysVTs5SPm0lF6ro',
    appId: '1:957338800443:web:c97c682ea04a840f7ce71e',
    messagingSenderId: '957338800443',
    projectId: 'tp3-firebase-ac93e',
    authDomain: 'tp3-firebase-ac93e.firebaseapp.com',
    storageBucket: 'tp3-firebase-ac93e.appspot.com',
    measurementId: 'G-V5CJDQZE51',
  );
}
